---
stages:
  - update
  - lint
  - test
  - lsif
  - publish
  - propagate

include:
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/all.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/publish.gitlab-ci.yml
